export const dataset = {
"property":"tài sản",
"wood":"gỗ",
"building":"công trình xây dựng",
"textile":"hàng dệt may",
"plant":"thực vật",
"house":"ngôi nhà",
"interior design":"thiết kế nội thất",
"floor":"sàn nhà",
"flooring":"ván sàn",
"hardwood":"gỗ cứng",
"wall":"tường",
"comfort":"sự thoải mái",
"real estate":"địa ốc",
"table":"cái bàn",
"living room":"phòng khách",
"chair":"cái ghế",
"wood stain": "vết gỗ",
"room":"căn phòng",
"home":"nhà",
"wood flooring":"sàn gỗ",
"houseplant":"cây đặt trong nhà",
"linens":"khăn trải giường",
"landscape":"phong cảnh",
"font":"phông",
"bedding":"chăn ga gối đệm",
"outdoor furniture":"đồ đạc ngoài trời",
"bed frame":"khung giường",
"ceiling":"trần nhà",
"bedroom":"phòng ngủ",
"art":"tác phẩm nghệ thuật",
"window treatment":"đồ trang trí cửa sổ",
"bottle":"cái chai",
"liquid":"chất lỏng",
"water":"nước",
"water bottle":"chai nước",
"fluid":"dung dịch",
"plastic bottle":"chai nhựa",
"bottle cap":"nắp chai",
"drinking water":"nước uống",
"plastic":"nhựa",
"solvent":"dung môi",
"gas":"khí ga",
"drinkware":"đồ uống",
"drink":"uống",
"electric blue":"màu xanh điện",
"solution":"lời giải",
"science":"khoa học",
"transparency":"trong suốt",
"soft drink":"thức uống có ga",
"countertop":"mặt bàn",
"food":"thức ăn",
"cabinetry":"tủ đựng đồ",
"kitchen appliance":"đồ dùng nhà bếp",
"kitchen":"nhà bếp",
"tableware":"bộ đồ ăn",
"home appliance":"đồ gia dụng",
"kitchen stove":"bếp lò",
"cuisine":"ẩm thực",
"major appliance":"vật dụng chính",
"cooking":"nấu ăn",
"stove":"bếp",
"recipe":"công thức nấu ăn",
"small appliance":"vật dụng nhỏ",
"cooktop":"bếp nấu",
"rectangle":"hình chữ nhật",
"gas stove":"bếp ga",
"cookware and bakeware":"dụng cụ nấu ăn và dụng cụ làm bánh",
"drawer":"ngăn kéo",
"kitchen appliance accessory":"phụ kiện thiết bị nhà bếp",
"machine":"máy móc",
"crock":"bát đĩa bằng sành",
"food storage containers":"hộp đựng thực phẩm",
"aluminium":"nhôm",
"stock pot":"nồi kho",
"mixer":"máy trộn",
"still life photography":"ảnh tĩnh vật",
"saucepan":"cái chảo",
"household hardware":"phần cứng gia dụng",
"yellow":"màu vàng",
"gadget":"đồ tiện ích",
"passive circuit component":"thành phần mạch thụ động",
"electronic device":"thiết bị điện tử",
"technology":"công nghệ",
"electronic component":"thành phần điện tử",
"computer hardware":"phần cứng máy tính",
"pattern":"khuôn mẫu",
"office equipment":"thiết bị văn phòng",
"electronic engineering":"kỹ thuật điện tử",
"engineering":"ngành kỹ thuật",
"computer component":"thành phần máy tính",
"personal computer hardware":"phần cứng máy tính cá nhân",
"wire":"dây điện",
"electronic instrument":"nhạc cụ điện tử",
"collection":"bộ sưu tập",
"electrical network":"mạng điện tử",
"electronics":"đồ điện tử",
"visual arts":"nghệ thuật tạo hình",
"circuit prototyping":"tạo mẫu mạch",
"computer keyboard":"bàn phím máy tính",
"mouse":"chuột máy tính",
"input device":"thiết bị đầu vào",
"space bar":"phím cách",
"peripheral":"thiết bị ngoại vi",
"numeric keypad":"bàn phím số",
"laptop accessory":"phụ kiện laptop",
"composite material":"nguyên liệu hỗn hợp",
"event":"sự kiện",
"office supplies":"văn phòng phẩm",
"number":"số",
"communication device":"thiết bị giao tiếp",
"multimedia":"đa phương tiện",
"remote control":"điều khiển từ xa",
"electronics accessory":"phụ kiện điện tử",
"magenta":"màu đỏ tươi",
"circle":"hình tròn",
"musical instrument accessory":"phụ kiện nhạc cụ",
"ceiling fan":"quạt trần",
"mechanical fan":"quạt cơ khí",
"insect":"côn trùng",
"wing":"cánh",
"metal":"kim loại",
"balance":"cân bằng",
"product":"sản phẩm",
"ball":"quả bóng",
"car":"xe hơi",
"orange":"màu cam",
"wheel":"bánh xe",
"food group":"nhóm thức ăn",
"games":"trò chơi",
"toy":"đồ chơi",
"motor vehicle":"phương tiện xe máy",
"collage":"cắt dán",
"design":"thiết kế",
"screenshot":"ảnh chụp màn hình",
"fashion accessory":"phụ kiện thời trang",
"illustration":"mô phỏng",
"automotive lighting":"chiếu sáng ô tô",
"graphics":"đồ họa",
"graphics design":"thiết kế đồ họa",
"vehicle door":"cửa phương tiện",
"toy vehicle":"xe đồ chơi",
"comfort food":"thức ăn thoải mái",
"automotive exterior":"ngoại thất ô tô",
"family car":"xe gia đình",
"baby toys":"đồ chơi trẻ em",
"button":"cúc áo",
"organism":"sinh vật",
"watch":"đồng hồ",
"gesture":"cử chỉ",
"portable communication device":"thiết bị liên lạc di động",
"mobile phone":"điện thoại di động",
"output device":"thiết bị đầu ra",
"telephony":"điện thoại",
"audio equipment":"thiết bị âm thanh",
"mobile device":"thiết bị di động",
"telephone":"điện thoại",
"smartphone":"điện thoại thông minh",
"brand":"thương hiệu",
"mobile phone case":"ốp lưng điện thoại",
"strap":"dây đeo",
"everyday carry":"đồ mang theo hàng ngày",
"mobile phone accessories":"phụ kiện điện thoại",
"display device":"thiết bị hiển thị",
"logo":"lôgô",
"calculator":"máy tính cầm tay",
"writing implement":"dụng cụ viết",
"stationery":"văn phòng phẩm",
"pencil":"bút chì",
"tablet computer":"máy tính bảng",
"paper product":"sản phẩm giấy",
"musical instrument":"nhạc cụ",
"writing instrument accessory":"phụ kiện dụng cụ viết",
"pen":"bút mực",
"ball pen":"bút bi",
"titanium":"titanium",
"picture frame":"khung ảnh",
"brush":"cái chải",
"cosmetics":"mỹ phẩm",
"paper":"giấy",
"paint":"sơn",
"helmet":"mũ bảo hiểm",
"head":"cái đầu",
"sports equipment":"thiết bị thể thao",
"sports gear":"dụng cụ thể thao",
"personal protective equipment":"thiết bị bảo vệ cá nhân",
"synthetic rubber":"cao su tổng hợp",
"automotive design":"thiết kế ô tô",
"carmine":"thoa son",
"fictional character":"nhân vật hư cấu",
"eyewear":"kính mắt",
"hat":"nón",
"sun hat":"nón che nắng",
"fedora":"mũ phớt",
"costume hat":"mũ trang phục",
"beige":"màu be",
"costume accessory":"phụ kiện trang phục",
"tennis":"quần vợt",
"strings":"dây chỉ",
"racketlon": "cây vợt",
"racket":"cây vợt",
"tennis equipment":"trang bị quần vợt",
"racquet sport":"thể thao dùng vợt",
"tennis racket":"vợt tennis",
"tennis racket accessory":"phụ kiện vợt tennis",
"net":"lưới",
"ball game":"trò chơi với bóng",
"soft tennis":"quần vợt mềm",
"sports":"thể thao",
"cap":"nón lưỡi trai",
"headgear":"mũ đội đầu",
"baseball cap":"mũ bóng chày",
"cricket cap": "mũ chơi cricket",
"computer":"máy tính",
"personal computer":"máy tính cá nhân",
"material property":"tài sản vật chất",
"flower":"hoa",
"flowerpot":"chậu hoa",
"petal":"cánh hoa",
"laptop":"máy tính xách tay",
"black":"màu đen",
"tints and shades":"sắc thái của màu",
"frozen dessert":"món tráng miệng đông lạnh",
"ingredient":"nguyên liệu",
"cone":"hình nón",
"poster":"áp phích",
"happy":"vui vẻ",
"hood":"mui xe",
"bumper":"cản xe",
"personal luxury car":"xe cá nhân sang trọng",
"produce":"sản xuất",
"banana family":"chuối",
"staple food":"lương thực",
"vegetable":"rau củ",
"squash":"bí đao",
"fruit":"trái cây",
"natural foods":"thức ăn tự nhiên",
"computer desk":"máy tính để bàn",
"laser printing":"in laze",
"desk":"bàn làm việc",
"handwriting":"chữ viết tay",
"projection screen":"màn hình máy chiếu",
"public speaking":"nói trước công chúng",
"presentation":"thuyết trình",
"stage equipment":"trang bị sân khấu",
"forehead":"trán",
"eyebrow":"lông mày",
"shoulder":"vai",
"mouth":"miệng",
"jaw":"hàm",
"standing":"đứng",
"eyelash":"lông mi",
"smile":"nụ cười",
"vase":"lọ cắm hoa",
"dishware":"bộ đồ ăn",
"serveware":"đồ phục vụ",
"porcelain":"đồ sứ",
"artifact":"hiện vật",
"pottery":"đồ gốm",
"ceramic":"gốm sứ",
"pint glass":"ly thủy tinh",
"glass":"thủy tinh",
"cylinder":"hình trụ",
"barware":"đồ dùng quầy bar",
"highball glass":"kính bóng",
"clock":"đồng hồ",
"quartz clock":"đồng hồ thạch anh",
"wall clock":"đồng hồ treo tường",
"slope":"con dốc",
"vehicle":"phương tiện",
"motorcycle accessories":"phụ kiện xe máy",
"creative arts":"tác phẩm sáng tạo",
"rose":"hoa hồng",

}